version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/merchshop
      - SESSION_SECRET=your-secret-key-here
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    depends_on:
      - db
    volumes:
      - .:/app
    command: python main.py

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=merchshop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
